---
title: "Welsh School Funding"
output: html_document
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This notebook explores the Welsh schools funding data.

```{r message=FALSE, warning=FALSE}

library(dplyr)
library(ggplot2)
library(googlesheets)
library(knitr)
library(scales)
library(stringr)
library(tidyr)

source('schools.R')

#schools_raw <- load_local_authority_sheet("Torfaen")
#schools_tidy <- load_all()
```

```{r message=FALSE, warning=FALSE}
la_report = "Torfaen"
```

## Summary

Primary school sizes

```{r}
kable(schools_tidy %>%
  filter(!is.na(local_authority)) %>%
  filter(!is.na(num_pupils)) %>%
  group_by(local_authority, year) %>%
  summarize(schools=n(), total_pupils=sum(num_pupils), smallest=min(num_pupils), largest=max(num_pupils), mean=round(mean(num_pupils), 0), median=round(median(num_pupils), 0)) %>%
  rename("Local authority" = local_authority, "Year" = year, "Schools" = schools, "Total pupils" = total_pupils, "Smallest" = smallest, "Largest" = largest, "Mean" = mean, "Median" = median))
```

Size distribution

```{r}
schools_tidy %>%
  filter(!is.na(local_authority)) %>%
  filter(year == '2018-19') %>%
  ggplot(aes(num_pupils)) +
  geom_histogram(binwidth=25, colour="black", fill="white") +
  facet_wrap(~ local_authority, ncol=2)
```

## Pupil funding vs. year

```{r}
plot_pupil_funding_vs_year(schools_tidy, la_report, save_to_file = TRUE)
```

## Total school delegated funding vs. number of pupils per school

```{r}
plot_school_funding_vs_size(schools_tidy, la_report, save_to_file = TRUE)
```

## Surplus and deficit vs. year

```{r}
plot_pupil_funding_vs_outturn(schools_tidy, la_report, save_to_file = TRUE)
```

## Pupil funding vs. free school meals

```{r}
plot_pupil_funding_vs_fsm(schools_tidy, la_report, save_to_file = TRUE)
```
